[0m14:39:55.751270 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a963f6d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a96a5f5f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a96a5e090>]}


============================== 14:39:55.762861 | 406439db-5548-4181-955d-60683c98db09 ==============================
[0m14:39:55.762861 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:39:55.763901 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/gcpavril/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:39:55.764834 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/gcpavril/dbt-bigquery-project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:39:55.767750 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.13110831, "process_in_blocks": "46016", "process_kernel_time": 0.40107, "process_mem_max_rss": "92844", "process_out_blocks": "8", "process_user_time": 2.220091}
[0m14:39:55.768688 [debug] [MainThread]: Command `dbt test` failed at 14:39:55.768503 after 0.13 seconds
[0m14:39:55.769343 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a962c2ae0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a961b3290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793a963f6d80>]}
[0m14:39:55.770023 [debug] [MainThread]: Flushing usage events
[0m14:39:56.121545 [debug] [MainThread]: An error was encountered while trying to flush usage events
